### ISSUE TITLE
Antivirus Detection

### ISSUE THREAD

**Issue by brainygeek09** [mustafadalga/wildlogger#1]
Keylogger is being detected by new update of Windows Defender. Please how can you help on this matter? Thanks in anticipation!

**Comment by mustafadalga** [comment]
Hi @bhimbolar ,
As a solution, you can research antivirus bypass techniques.

A crypter is a software tool that can encrypt, obfuscate, and manipulate malware, making it undetectable to security programs.

For more information, you can review the source of [trend micro](https://www.trendmicro.com/vinfo/my/security/definition/Crypter).

**Comment by mustafadalga** [comment]
Question answered.
